### ISSUE TITLE
Is the rezero have no better performance than orig ?

### ISSUE THREAD

**Issue by Johnson-yue** [fabio-deep/ReZero-ResNet#1]

**Comment by fabio-deep** [comment]
From the (limited) experiments we can see that rezero improves convergence speed in all cases, and can improve final performance in deeper networks compared to the original.

**Comment by jiang-yuan** [comment]
> 
> 
> From the (limited) experiments we can see that rezero improves convergence speed in all cases, and can improve final performance in deeper networks compared to the original.

According to your table, even though Rezero spends less epoch to converge, it still not significantlly reduce the running time as the epoch number reduction. Does it mean Rezero needs more time to run an epoch?
Besides, it seems Rezero does not speed up in ResNet101, do you know why?

**Comment by fabio-deep** [comment]
I ran these experiments a while ago but from what I can remember they were ran on different machines/GPUs, so comparing runtime isn't entirely fair here. In an A/B runtime test I would expect ReZero to be slightly slower than without it.

Hope that helps

**Comment by jiang-yuan** [comment]
> 
> 
> I ran these experiments a while ago but from what I can remember they were ran on different machines/GPUs, so comparing runtime isn't entirely fair here. In an A/B runtime test I would expect ReZero to be slightly slower than without it.
> 
> Hope that helps

Thank you.
You mean that Rezero is slightly slower but the result with Rezero is slightly better.
Therefore, Rezero cannot achieve a fast convergence in your setting. Sad.

**Comment by jiang-yuan** [comment]
Besides, the author said that they use lamb optimizer in their experiment. Maybe this will also contribute to the result.

**Comment by fabio-deep** [comment]
Yes maybe you're right, you could try it out
